[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_20']

[phases.build]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci',
    'npm run build',
    'php artisan migrate --force'
]

[phases.deploy]
cmds = []

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'