[phases.setup]
nixPkgs = [
    'php82',
    'php82Extensions.pdo_mysql',
    'php82Extensions.mbstring',
    'php82Extensions.tokenizer',
    'php82Extensions.xml',
    'php82Extensions.curl',
    'php82Extensions.gd',
    'php82Extensions.zip',
    'php82Packages.composer',
    'nodejs_20'
]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader --ignore-platform-req=ext-gd",
    "npm ci",
    "npm run build",
    "php artisan migrate --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"